/** DO NOT EDIT THIS FILE. **/
var courses = [
  {
    id: 'MATH08057',
    name: 'Introduction to Linear Algebra',
    assessments: [
      {
        id: 'MATH08057-01',
        name: 'Exam',
        weight: 0.666667,
        mark: 68
      },
      {
        id: 'MATH08057-02',
        name: 'Coursework',
        weight: 0.333333,
        mark: 74
      }
    ],
    topics: ['Algebra', 'Analysis'],
    readingList: []
  },
  {
    id: 'INFR08022',
    name: 'Computer Programming Skills and Concepts',
    assessments: [
      {
        id: 'INFR08022-01',
        name: 'Exam',
        weight: 0.75,
        mark: 84
      },
      {
        id: 'INFR08022-02',
        name: 'Presentation',
        weight: 0.15,
        mark: 71
      },
      {
        id: 'INFR08022-02',
        name: 'Class test',
        weight: 0.1,
        mark: 58
      }
    ],
    topics: ['Programming', 'Abstraction', 'UNIX'],
    readingList: [
      {
        id: '00010',
        dueDate: '2019-10-29',
        title: 'A Book on C (4th Edition)',
        author: 'Kelley & Pohl',
        image: 'cbook.jpg'
      },
      {
        id: '00020',
        dueDate: '2019-10-01',
        title: 'The C Programming Language',
        author: 'B.Kernighan & D.Ricthie',
        image: 'clang.jpg'
      },
      {
        id: '00030',
        dueDate: '2019-09-20',
        title: 'The Craft of Functional Programming',
        author: 'Simon Thompson',
        image: 'craft.jpg'
      },
      {
        id: '00040',
        dueDate: '2019-10-22',
        title: 'An Introduction to Neural Networds',
        author: 'Kevin Gurney',
		    image: null
      }
    ]
  }
];
